<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(MineEngineTargetFramework)</TargetFramework>
    <RootNamespace>MineEngine.Build</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MineEngine.Core\MineEngine.Core.csproj" />
    <ProjectReference Include="..\MineEngine.Project\MineEngine.Project.csproj" />
    <ProjectReference Include="..\MineEngine.IR\MineEngine.IR.csproj" />
    <ProjectReference Include="..\MineEngine.Minecraft\MineEngine.Minecraft.csproj" />
    <ProjectReference Include="..\MineEngine.Generator\MineEngine.Generator.csproj" />
  </ItemGroup>

</Project>
